# config.py
# 与精准增强版核心参数保持一致
STRATEGY_CONFIG = {
    "MA_SHORT": 5,          # 默认短期均线（与核心文件默认值一致）
    "MA_LONG": 20,          # 默认长期均线
    "SUPPORT_RESIST_DAYS": 5,  # 支撑阻力周期
    "LIMIT_UP_DOWN": 0.1,   # 涨跌停比例
    "BUY_MARGIN": 0.01,     # 买入容忍度
    "SELL_MARGIN": 0.01,    # 卖出容忍度
    "AUTO_ADJUST": True     # 前复权
}

# 标的配置（用于main.py独立运行）
TARGET_SYMBOL = "000333"
TARGET_STOCK_NAME = "美的集团（深市，家电龙头）"

# 市场信息
MARKET_TYPE = "中国A股"
CURRENCY = "人民币（CNY）"
TRADING_HOURS = "北京时间 9:30-11:30 | 13:00-15:00"

# 快捷引用
MA_SHORT = STRATEGY_CONFIG["MA_SHORT"]
MA_LONG = STRATEGY_CONFIG["MA_LONG"]
SUPPORT_RESIST_DAYS = STRATEGY_CONFIG["SUPPORT_RESIST_DAYS"]
LIMIT_UP_DOWN = STRATEGY_CONFIG["LIMIT_UP_DOWN"]
BUY_MARGIN = STRATEGY_CONFIG["BUY_MARGIN"]
SELL_MARGIN = STRATEGY_CONFIG["SELL_MARGIN"]
AUTO_ADJUST = STRATEGY_CONFIG["AUTO_ADJUST"]